### ISSUE TITLE
ODK XLSForm Offline Errors:

### ISSUE THREAD

**Issue by tkiptuyo** [opendatakit/xlsform-offline#32]
ODK XLSForm Offline Errors:
[row : 997] Question with no type.
{u'choice_filter': u'Migori', u'instance': {u'odk:tag': u'Ondong Dispensary'}, u'hint': u'Suna_East', u'label': u'Kenya'}

**Comment by yanokwa** [comment]
Thanks for filing this. It's an issue with pyxform upstream and I've filed the upstream issue at https://github.com/XLSForm/pyxform/issues/352 and I'll close this one once upstream is fixed.

As a short term fix, use the previous version ([v1.10.0](https://github.com/opendatakit/xlsform-offline/releases/tag/v1.10.0)).

**Comment by yanokwa** [comment]
Fixed with #33
